version: '3'
services:

  camunda-postgres:
    image: postgres:9.6
    hostname: postgres
    domainname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=camunda
      - POSTGRES_USER=camunda
      - POSTGRES_PASSWORD=camunda
    networks:
      - compose_glaston_camunda

  zookeeper:
    image: zookeeper:3.4.13
    ports:
      - "2181:2181"
      - "2888"
    networks:
      - compose_glaston_camunda

  kafka:
    image: wurstmeister/kafka:2.12-2.1.0
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - compose_glaston_camunda

networks:
  compose_glaston_camunda:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.163.252.0/16
