version: '3'
services:
  camunda:
    image: camunda/camunda-bpm-platform:run-latest
    command: bash -c "./start.sh --rest --swaggerui --webapps"
    ports:
      - "8084:8080"
    volumes:
      - ./docker-files/bpmns/:/camunda/configuration/resources/:ro
    networks:
      - compose_glaston_camunda

networks:
  compose_glaston_camunda:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.163.252.0/16